apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-v1.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: victoriar18/hello-gitops
  newTag: 66a4446619f8d52befed5ee5dc9ab869fc938fd7
