apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-v1.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: victoriar18/hello-gitops
  newTag: 2d166792a73e3acb12bbff97adc9631b6754c5f2
