apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-v1.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: victoriar18/hello-gitops
  newTag: 2755c0b2be8565cc6991c6978d9365d47f8c7fb9
